// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8LNUcUru2LbFcJXf1RuhTlJY7HqWGqB0',
    appId: '1:39187469866:web:db9e553a65a02e97d4d553',
    messagingSenderId: '39187469866',
    projectId: 'ditonton-modular',
    authDomain: 'ditonton-modular.firebaseapp.com',
    storageBucket: 'ditonton-modular.appspot.com',
    measurementId: 'G-MDPED2Y8L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDtqK1aD3J8e_Wa3Otth8nDDxUvah2HSs',
    appId: '1:39187469866:android:5c0567a2de8728cfd4d553',
    messagingSenderId: '39187469866',
    projectId: 'ditonton-modular',
    storageBucket: 'ditonton-modular.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa3mYypv8aiIx8w5hhEEwLzfNctjmgGUc',
    appId: '1:39187469866:ios:4643c833f1b93979d4d553',
    messagingSenderId: '39187469866',
    projectId: 'ditonton-modular',
    storageBucket: 'ditonton-modular.appspot.com',
    iosClientId: '39187469866-o4vsddkbjtuni5mdeauc66nevkcq9957.apps.googleusercontent.com',
    iosBundleId: 'com.example.ditontonModular',
  );
}
